apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api
  labels:
    app: kubernetes-demo-api
spec:
  # Select the pods with label 'app: kubernetes-demo-api'
  selector:
    app: kubernetes-demo-api
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000  # Container port
      # nodePort: 32000  # Optional: uncomment to use a fixed NodePort in range 30000-32767
  type: NodePort # change to LoadBalancer if on a cloud provider